name: sp_initials_example
description: This plugin returns initial letters of the full name with customizable background, so it can be useful while creating contacts or chat application.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sp_initials:
   
    path: ../


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

 
  uses-material-design: true