name: sp_initials
description: This plugin returns initial letters of the full name with customizable background, so it can be useful while creating contacts or chat application.
version: 0.0.4
# author: shankar-pariyar
homepage: https://github.com/shankar-pariyar/SpInitials

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  plugin:
    platforms:
      android:
        package: com.shankarpariyar.sp_initials
        pluginClass: SpInitialsPlugin
      ios:
        pluginClass: SpInitialsPlugin
